"""initial migration

Revision ID: 2db1917b9503
Revises: 1e28df51ee28
Create Date: 2015-07-14 13:49:31.562000

"""

# revision identifiers, used by Alembic.
revision = '2db1917b9503'
down_revision = '1e28df51ee28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
